[package]
name = "fmde"
version = "0.1.0"
edition = "2024"
default-run = "fmde"

[[bin]]
name = "rom-to-text"
path = "src/utilities/rom-to-text.rs"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
crc = "3.2.1"
csv = "1.3.1"
